-- DROP USER DEMOUSER;

CREATE USER DEMOUSER
-- IDENTIFIED BY <password>
;

CREATE TABLE "DEMOUSER"."DimCustomer" 
   (	"CUSTOMER_ID" NUMBER(*,0), 
	"NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"PHONE_NO" NUMBER(*,0) NOT NULL ENABLE, 
	"EMAIL" NVARCHAR2(50), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UNIQUE_CUSTOMER" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE TABLE "DEMOUSER"."DimItem" 
   (	"ITEM_ID" NUMBER(*,0), 
	"ITEM_CATEGORY_ID" NUMBER(*,0), 
	"ITEM_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"UNITPRICE" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."DimItem" ADD CONSTRAINT "DIMITEM_DIMITEMCATEGORY_FK" FOREIGN KEY ("ITEM_CATEGORY_ID")
	  REFERENCES "DEMOUSER"."DimItemCategory" ("ITEM_CATEGORY_ID") ENABLE;
;

CREATE TABLE "DEMOUSER"."DimItemCategory" 
   (	"ITEM_CATEGORY_ID" NUMBER(*,0), 
	"ITEM_CATEGORY_NAME" NVARCHAR2(50), 
	"ITEM_CATEGORY_DESCRIP" NVARCHAR2(50), 
	"ACTIVE" NVARCHAR2(50), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("ITEM_CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEMOUSER"."EMP_VIEW" ("EMP_NAME", "SALARY") AS 
  SELECT EMP_NAME , SALARY FROM EmpLAT;
;

CREATE TABLE "DEMOUSER"."FACTINVENTORY" 
   (	"INVENT_ID" NUMBER(*,0), 
	"ITEM_ID" NUMBER(*,0), 
	"QUANTITY_ON_HAND" NUMBER(*,0), 
	"MIN_STOCK" NUMBER(*,0), 
	"DATE_CREATED" DATE, 
	"ACTIVE" VARCHAR2(50), 
	 PRIMARY KEY ("INVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."FACTINVENTORY" ADD CONSTRAINT "FACTINVENTORY_DIMITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "DEMOUSER"."DimItem" ("ITEM_ID") ENABLE;
;

CREATE TABLE "DEMOUSER"."FACTINVENTORY_TRANSACTIONS" 
   (	"TRANSID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"TRANS_TYPE" NVARCHAR2(10), 
	"DATE_CREATED" DATE, 
	 PRIMARY KEY ("TRANSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."FACTINVENTORY_TRANSACTIONS" ADD CONSTRAINT "FACTINVEN_TRANSAC_DIMITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "DEMOUSER"."DimItem" ("ITEM_ID") ENABLE;
;

CREATE TABLE "DEMOUSER"."FactOrder" 
   (	"ORDER_ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"ORDER_DATE" DATE, 
	"ORDER_STATUS" NVARCHAR2(50), 
	"TOTAL_AMOUNT" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."FactOrder" ADD CONSTRAINT "FACTORDER_FACTORDERDETAIL_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "DEMOUSER"."FactOrderDetail" ("ORDER_ID") ENABLE;
  ALTER TABLE "DEMOUSER"."FactOrder" ADD CONSTRAINT "FACTORDER_DIMCUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "DEMOUSER"."DimCustomer" ("CUSTOMER_ID") ENABLE;
;

CREATE TABLE "DEMOUSER"."FactOrderDetail" 
   (	"ORDER_ID" NUMBER(*,0), 
	"ITEM_ID" NUMBER(*,0), 
	"QUANTITY" NUMBER(*,0), 
	"PRICE_AT_PURCHASE" NUMBER(*,0), 
	"ORDER_DETAIL_ID" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."FactOrderDetail" ADD CONSTRAINT "FK_ORDER_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "DEMOUSER"."DimItem" ("ITEM_ID") ENABLE;
  ALTER TABLE "DEMOUSER"."FactOrderDetail" ADD CONSTRAINT "FACTORDERDETAIL_FACTORDER_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "DEMOUSER"."FactOrder" ("ORDER_ID") ENABLE;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEMOUSER"."GET_LOW_STOCK_ALERTS" ("ITEM_NAME", "QUANTITY_ON_HAND", "MIN_STOCK") AS 
  SELECT item.ITEM_NAME, inventory.QUANTITY_ON_HAND, inventory.MIN_STOCK  FROM 
DEMOUSER.FACTINVENTORY inventory JOIN DEMOUSER."DimItem" item 
ON inventory.ITEM_ID = item.ITEM_ID
WHERE inventory.QUANTITY_ON_HAND < inventory.MIN_STOCK ;
;

CREATE TABLE "DEMOUSER"."PURCHASE_ORDER" 
   (	"P_O_ID" NUMBER, 
	"SUPPLIER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"STATUS" NVARCHAR2(10), 
	"ITEM_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "DEMOUSER"."PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_DIMITEM_FK" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "DEMOUSER"."DimItem" ("ITEM_ID") ENABLE;
  ALTER TABLE "DEMOUSER"."PURCHASE_ORDER" ADD CONSTRAINT "PURCHASE_ORDER_SUPPLIER_FK" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "DEMOUSER"."SUPPLIER" ("SUPPLIER_ID") ENABLE;
;

CREATE TABLE "DEMOUSER"."SUPPLIER" 
   (	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NAME" NVARCHAR2(10), 
	"PHONE_NO" NUMBER, 
	"LEAD_TIME" NUMBER, 
	 PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATECUSTOMER (name NVARCHAR2, phoneno NUMBER, email1 IN NVARCHAR2 )
 IS
 BEGIN
    INSERT INTO "DEMOUSER"."DimCustomer"( CUSTOMER_ID, NAME, PHONE_NO, EMAIL) 
    	VALUES(DEMOUSER.SEQ_CUSTOMER.NEXTVAL, name, phoneno, email1);
	COMMIT;
 END;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEFACTINVENTORY
 (
 	 itemId NUMBER,  
 	 quantityInHand NUMBER, 
 	 minStock NUMBER,
 	 active nvarchar2
 ) 
 IS
 BEGIN
	 
    INSERT INTO "DEMOUSER"."FACTINVENTORY"( INVENT_ID,ITEM_ID,QUANTITY_IN_HAND,MIN_STOCK,ACTIVE ) 
    	VALUES(DEMOUSER.SEQ_INVENTORY.NEXTVAL,itemId,quantityInHand,minStock,active);
	COMMIT;

 END ;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEFACTORDER
 (
     orderId NUMBER,
 	 customerId NUMBER,  
 	 orderDate DATE, 
 	 orderStatus  NVARCHAR2,
 	 totalAmount NUMBER
 	 
 ) 
 IS
 BEGIN
    INSERT INTO "DEMOUSER"."FactOrder"( ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT ) 
    	VALUES(DEMOUSER.SEQ_FACTORDER.NEXTVAL,customerId,orderDate,orderStatus,totalAmount);

	COMMIT;
 END;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEFACTORDERDEATILS
 (
     orderId  NUMBER,
 	 ItemId NUMBER,  
 	 quantity  NUMBER, 
 	 priceAtPurchase  NUMBER,
 	 orderDetailId NUMBER
 	 
 ) 
 IS
 BEGIN
    INSERT INTO "DEMOUSER"."FactOrderDetail"( ORDER_ID,ITEM_ID,QUANTITY,PRICE_AT_PURCHASE,ORDER_DETAIL_ID ) 
    	VALUES(DEMOUSER.SEQ_ORDERDETAIL.NEXTVAL,ItemId,quantity,priceAtPurchase,orderDetailId);

	COMMIT;
	

 END;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEITEM
 (
 	 item_category_id NUMBER,  
 	 item_name  NVARCHAR2, 
 	 unitprice NVARCHAR2,
 	 unit_instock NVARCHAR2
 ) 
 IS
 BEGIN
    INSERT INTO "DEMOUSER"."DimItem"( ITEM_ID, ITEM_CATEGORY_ID, ITEM_NAME,UNITPRICE,UNIT_INSTOCK ) 
    	VALUES(DEMOUSER.SEQ_ITEM.NEXTVAL, item_category_id, item_name,unitprice,unit_instock);

	COMMIT;
END ;
;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEITEMCATEGORY
(name nvarchar2, descript NVARCHAR2 ,active NVARCHAR2)
IS
BEGIN
	INSERT into "DEMOUSER"."DimItemCategory"( ITEM_CATEGORY_ID,ITEM_CATEGORY_NAME,ITEM_CATEGORY_DESCRIP,ACTIVE,DATE_CREATED )
	 values (DEMOUSER.SEQ_ITEMCATEGORY.NEXTVAL,name,descript,active,sysdate);
	 COMMIT;
END;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEITEMTRANSAC
 (
    trans_id NUMBER,
 	 item_id  NUMBER,  
 	 quanity NUMBER, 
 	 trans_type NVARCHAR2,
 	 date_created NUMBER
 	 
 	 
 ) 
 IS
 BEGIN
    INSERT INTO 'DEMOUSER'.'FACTINVEN_TRANSAC'( TRANSID,ITEM_ID,QUANTITY,TRANS_TYPE,DATE_CREATED ) 
    	VALUES(DEMOUSER.SEQ_ITEMTRANSAC.NEXTVAL,trans_id,item_date,quantity,trans_type,date_created);

	COMMIT;
	 END ;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEORDER ( custId NUMBER,  itemId NUMBER,  quantity NUMBER, PriceAtPurchase NUMBER, totalAmount NUMBER)
IS
BEGIN
	INSERT INTO DEMOUSER."FactOrder"(Order_ID, CUSTOMER_ID,  ORDER_STATUS, TOTAL_AMOUNT) 
					  VALUES(DEMOUSER.SEQ_ORDER.NEXTVAL, custId,  'COMPLETED', totalAmount );
	
	--DECLARE OrdID NUMBER; 
	--BEGIN
		--SELECT DEMOUSER.SEQ_ORDER.CURRVAL INTO OrdID FROM DUAL;
	--END;
	
	INSERT INTO DEMOUSER."FactOrderDetail" ( ORDER_DETAIL_ID, Order_ID, ITEM_ID,  Quantity, PRICE_AT_PURCHASE) 
					  VALUES( DEMOUSER.SEQ_ORDERDETAIL.NEXTVAL, DEMOUSER.SEQ_ORDER.CURRVAL, itemId,  quantity, PriceAtPurchase ) ;
	COMMIT;
END;
	    
	    
 ;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEORDERNEW ( custId NUMBER,  itemId NUMBER,  quantity NUMBER, PriceAtPurchase NUMBER)
IS
	OrdID NUMBER;
	totalAmount NUMBER;
BEGIN
	totalAmount := quantity * PriceAtPurchase;
	INSERT INTO DEMOUSER."FactOrder"(Order_ID, CUSTOMER_ID,  ORDER_STATUS, TOTAL_AMOUNT) 
					  VALUES(DEMOUSER.SEQ_ORDER.NEXTVAL, custId,  'COMPLETED', totalAmount );

	OrdID := DEMOUSER.SEQ_ORDER.CURRVAL ;
	
	INSERT INTO DEMOUSER."FactOrderDetail" ( ORDER_DETAIL_ID, Order_ID, ITEM_ID,  Quantity, PRICE_AT_PURCHASE) 
					  VALUES( DEMOUSER.SEQ_ORDERDETAIL.NEXTVAL, OrdID, itemId,  quantity, PriceAtPurchase ) ;
	COMMIT;
END;
;

CREATE OR REPLACE PROCEDURE DEMOUSER.CREATEPURCHASE_ORDER
 (
    trans_id NUMBER,
 	 item_id  NUMBER,  
 	 quanity NUMBER, 
 	 trans_type NVARCHAR2,
 	 date_created NUMBER
 	 
 	 
 ) 
 IS
 BEGIN
    INSERT INTO "DEMOUSER"."FACTINVEN_TRANSAC"( TRANSID,ITEM_ID,QUANTITY,TRANS_TYPE,DATE_CREATED ) 
    	VALUES(DEMOUSER.SEQ_ITEMTRANSAC.NEXTVAL,trans_id,item_date,quantity,trans_type,date_created);

	COMMIT;
	

 END ;

CREATE OR REPLACE PROCEDURE DEMOUSER.EMPLOYEE
 (
     userid  NUMBER,
 	 name NVARCHAR2,  
 	 Rolee  NVARCHAR2, 
 	 ContactDetails  NUMBER
 ) 
 IS
 BEGIN
    INSERT INTO "DimEmployee"( USERID,NAME, ROLE,CONTACTDETAILS) 
    	VALUES(DEMOUSER.SEQ_EMPLOYEE.NEXTVAL, name, Rolee, ContactDetails);

	COMMIT;

 END;

CREATE OR REPLACE PROCEDURE DEMOUSER.FACTORDER
 (
     orderId NUMBER,
 	 customerId  NUMBER,  
 	 orderDate  DATE, 
 	 orderStatus NVARCHAR2,
 	 totalAmount  NUMBER
 	 
 ) 
 IS
 BEGIN
    INSERT INTO "FactOrder"( ORDER_ID,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,TOTAL_AMOUNT ) 
    	VALUES(DEMOUSER.SEQ_FACTORDER.NEXTVAL,customerId,orderDate,orderStatus,totalAmount);

	COMMIT;
	

 END ;

CREATE OR REPLACE PROCEDURE DEMOUSER.PROCESS_STOCK_MOVEMENT(
ITEM_ID IN NUMBER,
Qty_Change IN NUMBER,
Trans_Type IN VARCHAR2
)
IS
BEGIN
	UPDATE DEMOUSER.FACTINVENTORY 
		SET QUANTITY_ON_HAND = QUANTITY_ON_HAND + Qty_Change ;
		
	INSERT INTO DEMOUSER.FACTINVENTORY_TRANSACTIONS (TRANSID, ITEM_ID, QUANTITY, TRANS_TYPE, DATE_CREATED)
	VALUES(0, ITEM_ID, Qty_Change, Trans_Type, sysdate);
COMMIT;
EXCEPTION
	WHEN OTHERS THEN 
		ROLLBACK;
END PROCESS_STOCK_MOVEMENT;
;

CREATE SEQUENCE DEMOUSER."ISEQ$$_76336" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DEMOUSER."ISEQ$$_76421" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_CUSTOMER INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 10 NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_EMPLOYEE INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_FACTORDER INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_INVENTORY INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_ITEM INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_ITEMCATEGORY INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_ITEMTRANSAC INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_ORDER INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 10 NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_ORDERDETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 10 NOORDER ;

CREATE SEQUENCE DEMOUSER.SEQ_PURCHASEORDER INCREMENT BY 1 MINVALUE 0 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;