spring.application.name=IMS

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=DEMOUSER
spring.datasource.password=welcome123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true